version: '3'

services:
  redis:
    image: redis/redis-stack-server:6.2.6-v17
    ports:
      - "6379:6379"

  chatbot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot_app
    ports:
      - "8501:8501"
    env_file:
      .env
    depends_on:
      - redis
