services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: langgraph_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chatbot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot_app
    ports:
      - "8501:8501"
    env_file:
      .env
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
